# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_require 'semantic'

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Runs all checks"
  lane :check do
    gradle(task: "check")
  end

  desc "Takes a release tag and updates changelog for the components package"
  lane :tag_release do
    begin
      sh("gh --version")
    rescue => exception
      UI.error exception
      UI.user_error!("Github CLI must be installed. See https://github.com/cli/cli")
    end

    UI.user_error!("You need to provide a Github Personal token via a `GITHUB_TOKEN` environment variable - you can create a new token on Github https://github.com/settings/tokens/new") unless !ENV["GITHUB_TOKEN"].nil?
    UI.user_error!("You need to provide the Bitrise token via a `BITRISE_TOKEN` environment variable - See the Bitrise docs for help https://devcenter.bitrise.io/api/authentication.") unless !ENV["BITRISE_TOKEN"].nil?
    UI.user_error!("You need to provide the Bitrise app slug for this repo via a `ANDROID_COMPONENTS_APP_SLUG` environment variable") unless !ENV["ANDROID_COMPONENTS_APP_SLUG"].nil?
    UI.user_error!("You need to provide the Bitrise release workflow ID this repo via a `ANDROID_COMPONENTS_RELEASE_WORKFLOW_ID` environment variable") unless !ENV["ANDROID_COMPONENTS_RELEASE_WORKFLOW_ID"].nil?

    # ensure repo is clean and on main
    ensure_git_status_clean
    ensure_git_branch(
      branch: 'main'
    )

    # pull latest changes and fetch tags
    git_pull

    # get current version
    current_tag = last_git_tag(pattern: "[0-9]*")
    version = Semantic::Version.new(current_tag)

    # prompt for bump type
    bump_type = UI.select(
      "Current version is #{current_tag}. What would you like to bump?",
      ["major", "minor", "patch"]
    )

    # increment version
    case bump_type
    when "major"
      tag = version.increment!(:major)
    when "minor"
      tag = version.increment!(:minor)
    else
      tag = version.increment!(:patch)
    end

    sh("git", "checkout", "-b", "tag/#{tag.to_string}")

    # update changelog
    stamp_changelog(changelog_path: 'components/CHANGELOG.md', section_identifier: tag.to_string)
    git_commit(path: "components/CHANGELOG.md", message: "Update CHANGELOG.md and tagging release")

    push_to_git_remote

    sh("gh", "pr", "create", "--title", "Release #{tag.to_string}", "--body", "")

    # take tag and push to remote
    add_git_tag(tag: tag.to_string)
    push_git_tags

    # update releases on Github
    changelog = read_changelog(
      changelog_path: 'components/CHANGELOG.md',
      section_identifier: "[#{tag}]",
      excluded_markdown_elements: []
    )
    set_github_release(
      repository_name: "hmrc/android-components",
      api_token: ENV["GITHUB_TOKEN"],
      name: tag.to_string,
      tag_name: tag.to_string,
      description: changelog
    )

    # start release process on CI
    sh("cd .. && sh release.sh '#{tag.to_string}'")
  end

  desc "Starts the release workflow on CI for the components-test package"
  lane :release_test_version do
    begin
      sh("gh --version")
    rescue => exception
      UI.error exception
      UI.user_error!("Github CLI must be installed. See https://github.com/cli/cli")
    end

    UI.user_error!("You need to provide a Github Personal token via a `GITHUB_TOKEN` environment variable - you can create a new token on Github https://github.com/settings/tokens/new") unless !ENV["GITHUB_TOKEN"].nil?
    UI.user_error!("You need to provide the Bitrise token via a `BITRISE_TOKEN` environment variable - See the Bitrise docs for help https://devcenter.bitrise.io/api/authentication.") unless !ENV["BITRISE_TOKEN"].nil?
    UI.user_error!("You need to provide the Bitrise app slug for this repo via a `ANDROID_COMPONENTS_APP_SLUG` environment variable") unless !ENV["ANDROID_COMPONENTS_APP_SLUG"].nil?
    UI.user_error!("You need to provide the Bitrise release workflow ID this repo via a `ANDROID_COMPONENTS_TEST_RELEASE_WORKFLOW_ID` environment variable") unless !ENV["ANDROID_COMPONENTS_TEST_RELEASE_WORKFLOW_ID"].nil?

    # check that the version has been bumped
    if UI.confirm("Have you updated the version in components-test/build.gradle?")
      UI.success "Nice work"
    else
      UI.user_error!("Please updated the version in components-test/build.gradle before publishing")
    end

    # ensure repo is clean and on main
    ensure_git_status_clean
    ensure_git_branch(
      branch: 'main'
    )

    # pull latest changes and fetch tags
    git_pull

    # start release process on CI
    sh("cd .. && sh release_test_version.sh")
  end

  desc "Publishes components library"
  lane :publish do
    ensure_git_status_clean

    check

    # build the app and upload to Github Packages
    gradle(task: 'components:clean')
    gradle(task: 'components:build')
    gradle(task: 'components:publishComponentsPublicationToGitHubPackagesRepository')
  end

  desc "Publishes components test library"
  lane :publish_test do
    # ensure repo is clean and on main
    ensure_git_status_clean
    ensure_git_branch(
      branch: 'main'
    )

    check

    # build the app and upload to Github Packages
    gradle(task: 'components-test:clean')
    gradle(task: 'components-test:build')
    gradle(task: 'components-test:publishComponentsPublicationToGitHubPackagesRepository')
  end

  desc "Starts an emulator and records new screenshots"
  lane :screenshot_record do
    automated_test_emulator_run(
      AVD_setup_path: "fastlane/avd_setup/Nexus6P.json",
      shell_task: "./gradlew clean executeScreenshotTests -Precord"
    )
  end

  desc "Starts an emulator and runs all device checks"
  lane :connectedCheck do
    automated_test_emulator_run(
      AVD_setup_path: "fastlane/avd_setup/Nexus6P.json",
      shell_task: "./gradlew clean executeScreenshotTests"
    )
  end

  desc "Runs the screenshot comparison"
  lane :screenshot_diff do |options|
    gradle(task: "copyVerificationFiles")
    gradle(task: "executeScreenshotTests", properties: {"runInstrumentation" => "false"})
  end

  desc "Takes a release tag and updates changelog for the components-compose package"
  lane :release_components_compose_version do
    begin
      sh("gh --version")
    rescue => exception
      UI.error exception
      UI.user_error!("Github CLI must be installed. See https://github.com/cli/cli")
    end

    UI.user_error!("You need to provide a Github Personal token via a `GITHUB_TOKEN` environment variable - you can create a new token on Github https://github.com/settings/tokens/new") unless !ENV["GITHUB_TOKEN"].nil?
    UI.user_error!("You need to provide the Bitrise token via a `BITRISE_TOKEN` environment variable - See the Bitrise docs for help https://devcenter.bitrise.io/api/authentication.") unless !ENV["BITRISE_TOKEN"].nil?
    UI.user_error!("You need to provide the Bitrise app slug for this repo via a `ANDROID_COMPONENTS_APP_SLUG` environment variable") unless !ENV["ANDROID_COMPONENTS_APP_SLUG"].nil?
    UI.user_error!("You need to provide the Bitrise release workflow ID this repo via a `ANDROID_COMPONENTS_COMPOSE_RELEASE_WORKFLOW_ID` environment variable") unless !ENV["ANDROID_COMPONENTS_COMPOSE_RELEASE_WORKFLOW_ID"].nil?

    # ensure repo is clean and on main
    ensure_git_status_clean
    ensure_git_branch(
      branch: 'main'
    )

    # pull latest changes and fetch tags
    git_pull

    # get current version
    current_tag = last_git_tag(pattern: "compose/*")
    current_tag.slice! "compose/"
    version = Semantic::Version.new(current_tag)

    # prompt for bump type
    bump_type = UI.select(
       "Current version is #{version}. What would you like to bump?",
       ["major", "minor", "patch"]
    )

    # increment version
    case bump_type
    when "major"
      version = version.increment!(:major)
    when "minor"
      version = version.increment!(:minor)
    else
      version = version.increment!(:patch)
    end

    sh("git", "checkout", "-b", "tag/compose_#{version}")

    # update changelog
    stamp_changelog(changelog_path: 'components-compose/CHANGELOG.md', section_identifier: version.to_string)
    git_commit(path: "components-compose/CHANGELOG.md", message: "Update CHANGELOG.md and tagging release")

    push_to_git_remote

    sh("gh", "pr", "create", "--title", "Release compose components #{version}", "--body", "")

    # take tag and push to remote
    tag = "compose/#{version}"
    add_git_tag(tag: tag)
    push_git_tags

    # update releases on Github
    changelog = read_changelog(
      changelog_path: 'components-compose/CHANGELOG.md',
      section_identifier: "[#{version}]",
      excluded_markdown_elements: []
    )
    set_github_release(
      repository_name: "hmrc/android-components",
      api_token: ENV["GITHUB_TOKEN"],
      name: tag,
      tag_name: tag,
      description: changelog
    )

    # start release process on CI
    sh("cd .. && sh release_compose.sh '#{tag}'")
  end

  desc "Publishes compose components library"
  lane :publish_components_compose do
    ensure_git_status_clean

    check

    # build the app and upload to Github Packages
    gradle(task: 'components-compose:clean')
    gradle(task: 'components-compose:build')
    gradle(task: 'components-compose:publishComponentsPublicationToGitHubPackagesRepository')
  end
end
